services:
  onnx:
    build:
      context: .
      dockerfile: gpu-tensorrt.Dockerfile
    command: [
       "--model-en", "nemo-parakeet-tdt-0.6b-v2",
#             "--model", "onnx-community/whisper-large-v3-turbo",
      "--uri", "tcp://0.0.0.0:10300",
    ]
    volumes:
      - ./local:/data
      - ./cache:/cache
    restart: unless-stopped
    ports:
      - "10300:10300"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]