services:
  onnx:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: [
       "--model", "nemo-parakeet-tdt-0.6b-v2",
      "--uri", "tcp://0.0.0.0:10300"
    ]
    volumes:
      - ./local:/data
    restart: unless-stopped
    ports:
      - "10300:10300"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]