name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_linux:
    name: "test on linux"
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: setup mise
        uses: jdx/mise-action@v2
      - name: restore packages
        run: mise exec uv -- uv sync --locked
      - name: test
        run: |
          mise run test
          mise run lint
        
